spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}

logging:
  level:
    com.semantictalent.finder: INFO
    org.springframework.ai: WARN
    root: WARN