-- Sample data for development and testing
-- Note: Embeddings are placeholder vectors - in production these would be generated by OpenAI

-- Sample profiles with diverse backgrounds
INSERT INTO profiles (full_name, headline, summary, location, industry, experience_level, skills, company_name, job_title, years_experience, embedding) VALUES 
('John Smith', 'Senior Java Developer & Spring Boot Expert', 'Experienced backend developer with 8 years in fintech. Specialized in microservices architecture, Spring Boot, and PostgreSQL. Led multiple high-performance trading systems.', 'New York, NY', 'Financial Services', 'Senior', ARRAY['Java', 'Spring Boot', 'PostgreSQL', 'AWS', 'Microservices', 'Docker', 'Kubernetes'], 'Goldman Sachs', 'Senior Software Engineer', 8, '[0.1, 0.2, 0.3]'::vector),

('Sarah Johnson', 'Full Stack Engineer | React & Node.js Specialist', 'Full-stack developer with 5 years of experience building scalable web applications. Strong background in React, Node.js, and cloud technologies. Former startup CTO.', 'San Francisco, CA', 'Technology', 'Mid-Level', ARRAY['React', 'Node.js', 'TypeScript', 'MongoDB', 'AWS', 'GraphQL', 'Docker'], 'TechCorp', 'Full Stack Developer', 5, '[0.2, 0.1, 0.4]'::vector),

('Michael Chen', 'DevOps Engineer | Kubernetes & Cloud Architecture', 'DevOps specialist with expertise in container orchestration and cloud infrastructure. 6 years of experience automating deployment pipelines and managing large-scale systems.', 'Seattle, WA', 'Technology', 'Senior', ARRAY['Kubernetes', 'Docker', 'AWS', 'Terraform', 'Jenkins', 'Python', 'Linux'], 'Microsoft', 'Senior DevOps Engineer', 6, '[0.3, 0.4, 0.2]'::vector),

('Emily Rodriguez', 'Data Scientist | Machine Learning & Analytics', 'Data scientist with PhD in Statistics and 4 years of industry experience. Specialized in predictive modeling, natural language processing, and big data analytics.', 'Austin, TX', 'Healthcare', 'Mid-Level', ARRAY['Python', 'Machine Learning', 'TensorFlow', 'SQL', 'R', 'Pandas', 'Scikit-learn'], 'HealthTech Solutions', 'Senior Data Scientist', 4, '[0.4, 0.3, 0.1]'::vector),

('David Kim', 'Frontend Developer | React & UI/UX Expert', 'Creative frontend developer with strong design skills. 3 years of experience building responsive web applications with modern JavaScript frameworks and design systems.', 'Los Angeles, CA', 'Media & Entertainment', 'Junior', ARRAY['React', 'JavaScript', 'CSS', 'HTML', 'Figma', 'Tailwind CSS', 'Next.js'], 'Netflix', 'Frontend Developer', 3, '[0.1, 0.4, 0.3]'::vector),

('Lisa Wang', 'Product Manager | Fintech & Payments', 'Strategic product manager with 7 years of experience in financial technology. Expert in payment systems, regulatory compliance, and user experience optimization.', 'Chicago, IL', 'Financial Services', 'Senior', ARRAY['Product Management', 'Fintech', 'Agile', 'SQL', 'Analytics', 'Payments', 'Compliance'], 'Stripe', 'Senior Product Manager', 7, '[0.2, 0.3, 0.4]'::vector),

('Robert Brown', 'Mobile App Developer | iOS & Android', 'Cross-platform mobile developer with expertise in iOS and Android development. 5 years of experience building consumer and enterprise mobile applications.', 'Boston, MA', 'Technology', 'Mid-Level', ARRAY['Swift', 'Kotlin', 'React Native', 'iOS', 'Android', 'Flutter', 'Firebase'], 'Uber', 'Mobile Developer', 5, '[0.3, 0.2, 0.4]'::vector),

('Jennifer Lee', 'Cybersecurity Analyst | Threat Detection', 'Information security professional with expertise in threat detection and incident response. 4 years of experience protecting enterprise systems from cyber threats.', 'Washington, DC', 'Government', 'Mid-Level', ARRAY['Cybersecurity', 'Threat Detection', 'SIEM', 'Python', 'Linux', 'Incident Response', 'Risk Assessment'], 'Department of Defense', 'Cybersecurity Analyst', 4, '[0.4, 0.1, 0.2]'::vector),

('Thomas Anderson', 'Backend Engineer | Python & Django Specialist', 'Backend developer with deep expertise in Python ecosystem. 6 years of experience building scalable web services and APIs for e-commerce platforms.', 'Denver, CO', 'E-commerce', 'Senior', ARRAY['Python', 'Django', 'PostgreSQL', 'Redis', 'AWS', 'REST APIs', 'Celery'], 'Amazon', 'Senior Backend Engineer', 6, '[0.2, 0.4, 0.3]'::vector),

('Maria Garcia', 'UX/UI Designer | Design Systems Expert', 'User experience designer with 5 years of experience creating intuitive digital products. Specialized in design systems, user research, and accessibility.', 'Miami, FL', 'Design', 'Mid-Level', ARRAY['UX Design', 'UI Design', 'Figma', 'User Research', 'Prototyping', 'Design Systems', 'Accessibility'], 'Adobe', 'Senior UX Designer', 5, '[0.1, 0.3, 0.4]'::vector);

-- Sample search queries for analytics
INSERT INTO search_queries (query_text, user_ip, results_count, execution_time_ms, filters_applied) VALUES 
('Senior Java developers in fintech', '192.168.1.100', 5, 245, '{"industries": ["Financial Services"], "experienceLevel": "Senior"}'),
('React developers with startup experience', '192.168.1.101', 8, 312, '{"skills": ["React"]}'),
('Machine learning engineers', '192.168.1.102', 3, 189, '{"skills": ["Machine Learning"]}'),
('DevOps engineers with Kubernetes', '192.168.1.103', 4, 203, '{"skills": ["Kubernetes", "DevOps"]}'),
('Frontend developers in California', '192.168.1.104', 6, 287, '{"locations": ["San Francisco, CA", "Los Angeles, CA"]}');